name: hexlet-ci-app
on: push
jobs:
 my-job: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/make setup
      - uses: actions/make start
      - name: run tests
        run: make test 
      - run: make lint 