name: hexlet-ci-app
on: push
jobs:
 my-job: 
    runs-on: ubuntu-latest
    steps:
      - run: make setup
      - run: make start
      - name: run tests
        run: make test 
      - run: make lint 